### ISSUE TITLE
Cannot find name 'introjs'

### ISSUE THREAD

**Issue by CyrilEdison** [usablica/intro.js#877] opened 2018-07-26 08:30 UTC
## Description
After installation compiler shows " Cannot find name 'introjs' "

## Expected Behavior
Intro js installed but not working properly as it shows " Cannot find name 'introjs' "

**Comment by mbryant1988** [comment] 2018-08-13 19:26
I believe it may be named 'intro.js' instead of just 'introjs'

**Comment by bozdoz** [comment] 2018-08-14 01:34
Duplicate of #874?  Please confirm

**Closed** 2020-10-20 23:19 UTC
Labels: wontfix
