### ISSUE TITLE
The content is covered

### ISSUE THREAD

**Issue by xiaozhanghui** [usablica/intro.js#808] opened 2018-01-12 06:24 UTC
The content is covered
![tim 20180112142257](https://user-images.githubusercontent.com/23646391/34862208-2267ec54-f7a4-11e7-8074-77f890a0b263.png)

**Comment by mdahlke** [comment] 2018-01-17 05:29
@xiaozhanghui Any luck on this? I'm having the same issue with multiple versions (master, 1.7, 1.6).

**Comment by bozdoz** [comment] 2018-01-17 17:49
Duplicate of #123

**Closed by bozdoz** 2018-01-17 17:49 UTC

**Comment by xiaozhanghui** [comment] 2018-01-19 03:27
z-index conflict transform @mdahlke
