### ISSUE TITLE
exit() then start() then exit() => one overlay remains

### ISSUE THREAD

**Issue by ada3m0n666** [usablica/intro.js#548] opened 2016-03-01 16:32 UTC
for init purpose my application is initializing twice the same introJs() (for localization) in few milliseconds. But in the method _exitCode there is a setTimeOut for fadeout purpose.

Maybe it should be disable when calling manually exit method or adding eventually a parameter like this: 

function _exitIntro(targetElement, immedialty) {

    [....]
    if (immedialty === undefined || immedialty === false) {
        setTimeout(function () {
            if (overlayLayer.parentNode) {
                overlayLayer.parentNode.removeChild(overlayLayer);
            }
        }, 500);
    }
    else {
        if (overlayLayer.parentNode) {
            overlayLayer.parentNode.removeChild(overlayLayer);
        }
    }
[....]

}

or a customizable duration of the setTimeout (0 millisecond might execute immedialty)

**Comment by afshinm** [comment] 2016-09-12 21:18
I can't reproduce it. closing.

**Closed by afshinm** 2016-09-12 21:18 UTC
