### ISSUE TITLE
onexit gets called twice when you click the skip button

### ISSUE THREAD

**Issue by cssagogo** [usablica/intro.js#850] opened 2018-04-27 04:49 UTC
## Description
When you click the skip button the onexit function fires twice.  I would use onskip, but it does not get fired when you click the transparent background overlay.  I need a method of firing an event anytime the tour exits.

## Expected Behavior
The onexit function should only be called once.

## Actual Behavior
onexit is called twice 

## Example (recommended)

```
            var intro = introJs();
            intro.setOptions({
                overlayOpacity:     0.8,
                scrollToElement:    true,
                showBullets:        false,
                showProgress:       true,
                showStepNumbers:    false,
                disableInteraction: true,
                hidePrev:           true,
                hideNext:           true,
                doneLabel:          'Exit Tour',
                skipLabel:          'Exit Tour',
                steps:              this.getSteps()
            });
            intro.start();
            intro.onexit(function() {
                console.log('exit.tour');
            });
```

**Comment by cssagogo** [comment] 2018-04-27 05:13
As a work around I found I can use onbeforeexit

**Comment by jhorowitz-firedrum** [comment] 2018-06-22 22:41
Fixed in PR #871

**Comment by OAnouman** [comment] 2018-08-27 11:43
I got the same issue using version 2.9.3

**Comment by libattistella** [comment] 2019-07-27 00:26
Any update on this issue? I have this bug too in version 2.9.3

**Comment by subasically** [comment] 2019-08-16 14:48
I am experiencing this issue as well. Using version 2.9.3

**Comment by benelliott** [comment] 2020-10-14 00:00
bump

**Comment by AlbertMN** [comment] 2020-10-14 11:16
Still an issue. Using `onbeforeexit` instead is still a "fix"

**Comment by afshinm** [comment] 2020-10-17 09:42
Please install 3.0.1 and let me know if the issue is fixed. Thanks and apologies for the delay.

**Closed** 2020-10-17 09:42 UTC

**Comment by ayesha-iftikhar-relayr** [comment] 2021-03-21 01:10
@afshinm I'm currently using introjs `3.2.1`,  introjs-react `0.3.0`; and the issue still exists.
