### ISSUE TITLE
Highlighting box fails on fixed positioned elements. Stacking context problem.

### ISSUE THREAD

**Issue by kannojia** [usablica/intro.js#752] opened 2017-09-04 14:50 UTC
Hello,

When the element, which is to be highlighted, is contained within a fixed positioned parent. The element is overlapped by the dark overlay element.

**See this fiddle which reproduces this problem** : https://jsfiddle.net/c34qpcwy/
On the second step, the search element is overlapped by the overlay.

I know this is the related to the problem of stacking context and introjs handles this by setting the `z-index: auto`, `opacity: 1` etc. on positioned elements to remove the child stacking contexts formed. 
But this solution won't work for fixed positioned elements since the property `position: fixed` itself creates the new stacking context no matter what `z-index`, `opacity` and `transform` values are. ([See the third bullet in the scenario list](https://developer.mozilla.org/en/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context#The_stacking_context))

Any ideas how this can be solved ?

**Comment by bozdoz** [comment] 2017-09-04 17:21
This is clearly an issue with the library, and probably should be addressed somewhere.  

I would say that there is not a clear solution; not a solution that would work in every case; at least not how the current library works.

I personally have addressed this issue by removing the fixed elements on my pages, and I would recommend the same to you.  

The only solution I can think of for the library is to change the element's position to relative, and change its position on scroll or window resize (to make it work like it would as a fixed element).

We might be able to do this at some point down the road.  Thanks for your interest and helpful comments!

**Comment by bozdoz** [comment] 2017-09-04 17:30
Duplicate of #123

**Comment by do-web** [comment] 2017-09-13 19:50
Check out my pull request #747

**Closed** 2017-09-24 19:01 UTC
Labels: duplicate

**Comment by BroJenuel** [comment] 2022-06-25 16:19
any update on this? now is 2022, does it support fixed elements?
