### ISSUE TITLE
Stage number displaced

### ISSUE THREAD

**Issue by Bonsanto** [usablica/intro.js#381] opened 2014-12-11 20:35 UTC
I am using **bootstrap 3.3.1** and **intro.js 1.0.0** and the number of the stage that shows the element focused by the intro gets displaced when the **bootstrap.min.css** and the intro **introjs-nassim.css** are included in the same project. Do you have any hint, you can see the problem in the next pictures.

With both styles.

<p align="center">
<img src="https://dl.dropboxusercontent.com/u/6280514/ShareX/2014/12/2014-12-11_15-46-55.png"></img>
</p>

Without the bootstrap style.

<p align="center">
<img src="https://dl.dropboxusercontent.com/u/6280514/ShareX/2014/12/2014-12-11_15-51-24.png" align="center"></img>
</p>

**Comment by benthemonkey** [comment] 2016-02-09 01:34
Duplicate of #361

Another related PR: #468

**Closed** 2019-07-06 09:08 UTC
