### ISSUE TITLE
New Element Not Able To Be Selected

### ISSUE THREAD

**Issue by kmgilbert100** [usablica/intro.js#495] opened 2015-12-02 23:33 UTC
If a user makes an interaction, lets say open a new menu item.... I cannot select that new Element generated in the dom. Example trying to select something with a ID of `#testing` an element that gets generated during the process by user interaction (click). However the next step should be selecting this new element and I cannot do so....

I have even tried using `.refresh()`

Thanks in advance..

**Comment by masimakopoulos** [comment] 2015-12-14 20:51
This seems to be a duplicate of https://github.com/usablica/intro.js/issues/328

**Closed** 2020-10-20 23:19 UTC
Labels: wontfix
