### ISSUE TITLE
Intro.js doesn't position right when using transform: translate3d

### ISSUE THREAD

**Issue by BruceL33t** [usablica/intro.js#833] opened 2018-03-16 13:33 UTC
## Description
I found it impossible to position intro.js correctly on leaflet map dots and isolated the issue to being because they use translate3d.

## Expected Behavior
Correct placement of annotations

## Actual Behavior
Wrong placement on DOM elements with transform: translate3d(x,y,0)

## Example (recommended)
https://codepen.io/anon/pen/VXjoOQ

This is an overly simplified example, but if you comment out the line above transform: translate3d and try with top and left defined, you will see that it's working when not using transform: translate3d.

## Environment (optional)

Tested with latest chrome, firefox, latest intro.js, windows 10

**Comment by bozdoz** [comment] 2018-03-16 14:15
Duplicate of #123.  Transformations and positions all interfere with the stacking context.  We're looking into another solution that would work: #826

**Comment by BruceL33t** [comment] 2018-03-19 10:24
Hopefully that PR will soon be merged, and hopefully it solves all the positioning problems. :-)

**Comment by bozdoz** [comment] 2018-03-19 15:13
@BruceL33t Yeah, I'm not so sure.  The only questions I have about positioning is elements that have scrollbars, and guaranteeing that the black backdrop will fill all the way down to the bottom of the page.  To solve the second, the html tag can be positioned relative, but then the body can't necessarily be positioned relatively if its first or last children have top or bottom margins.  Haven't really looked into solving the first problem.

**Comment by sorenhoyer** [comment] 2018-03-19 17:14
@bozdoz Hmm so are you saying that there are no solutions to the problem with positioning not working for elements positioned with translate3d.

A bit surprising and disturbing to find a library as popular as this, not being able to do its most basic and essential thing - position overlays correctly.

**Comment by bozdoz** [comment] 2018-03-19 18:10
@sorenhoyer I agree with your second statement.  To your first statement, I referenced #826 as a solution, and perhaps the best solution anyone has come up with so far.  It would solve any stacking context problem, including translations.

Another solution off the top of my head was to clone the targeted element, and append the clone to the body element, so that we didn't have to be concerned with `z-index`; we'd have to be sure that we captured all inherited styles for that to work, but we'd also have to get its position relative to the page, and probably have to recalculate the `transform-origin` as well.  I'm not sure if anyone has attempted this, but I have seen this recommendation in an issue somewhere.

**Closed** 2020-10-20 20:19 UTC
Labels: duplicate, wontfix
