### ISSUE TITLE
Problem with fixed selectors

### ISSUE THREAD

**Issue by alvarotrigo** [usablica/intro.js#123] opened 2013-05-09 16:58 UTC
If I have a very large page (which enables me to scroll) and i have a fixed element at the bottom of the page, with something like:

``` css
position:fixed;
bottom:0px;
width:100%;
height:40px;
```

If i want to use the plugin with any element inside that fixed element, it will fail.
The plugin tries to scroll down to find it and ends up pointing to the wrong place.

**Comment by raduluchian** [comment] 2015-06-18 10:28
I also have a fixed navbar and have no such problem, on the other hand I have this problem with a fixed button:

    .btn {
        position: fixed:
        bottom: 0;
        right: 0;
    }

The problem is that the referenceLayer is always offset by minus some pixels to the top.

**Comment by afarineshfar** [comment] 2018-01-18 09:50
I have the same problem. I have to change position temporary to absolute and after close change it again. Maybe sometime this method help you especially when element fixed to top of page.

`
    function showIntro(){
        $("footer.fixed-footer-box").css("position", "absolute");
        
        var intro = introJs().setOptions({
            'nextLabel': 'Next Step',
            'prevLabel': 'Prev Step', 
            'skipLabel': 'Exit', 
            'doneLabel': 'Finish' 
        }).start();
        
        intro.onexit( function(){
            $("footer.fixed-footer-box").css("position", "fixed");
        });
    }
`

**Comment by bozdoz** [comment] 2018-02-27 17:23
duplicate of #109

**Closed** 2019-07-06 09:02 UTC
Labels: bug, duplicate
