### ISSUE TITLE
Resizing the page throws errors

### ISSUE THREAD

**Issue by plentylife** [usablica/intro.js#861] opened 2018-05-17 19:44 UTC
## Description
When resizing the page, there are TypeErrors that are thrown

## Expected Behavior
No errors occur

## Actual Behavior
This error is thrown
`Uncaught TypeError: Cannot read property 'style' of null
    at IntroJs._placeTooltip (index.js:14449)
    at IntroJs._refresh (index.js:14339)
    at IntroJs.refresh (index.js:16259)
    at IntroJs._onResize (index.js:14128)
    at handler (index.js:15422)`

**Comment by saumilcmarix** [comment] 2019-06-08 10:52
Hello,
I got a strange error if I click on tutorial multiple time, which says
Uncaught TypeError: Cannot read property 'setAttribute' of null
    at IntroJs._showElement (intro.js:1367)
    at IntroJs._nextStep (intro.js:444)
    at IntroJs._introForElement (intro.js:270)
    at IntroJs.start (intro.js:2370).

Please refer screenshot: [http://prntscr.com/nz73s6](url)

**Comment by gp0** [comment] 2019-11-15 05:03
I know this super-old, but i have just run into this. The cause seems to be that _onResize blindly tries to refresh, and if the .introjs-tooltip does not exist, it fails. I've worked around this with: 
`function _onResize () {
    if (document.querySelector('.introjs-tooltip') !== null) {
      this.refresh.call(this);
    }
  }`

**Comment by robsoncombr** [comment] 2020-03-01 09:34
Hello, I would like to register that I have also just run into this. On my case it happens inside _refresh():

Uncaught TypeError: Cannot read property 'style' of null
    at IntroJs._placeTooltip (intro.js?479f:603)
    at IntroJs._refresh (intro.js?479f:493)
    at IntroJs.refresh (intro.js?479f:2413)
    at IntroJs._onResize (intro.js?479f:282)
    at handler (intro.js?479f:1576)
    (..)

When it calls the following method with null values since the tooltip does not exist:
      _placeTooltip.call(this, this._introItems[this._currentStep].element, oldtooltipContainer, oldArrowLayer, oldHelperNumberLayer);

Can we please have this fixed in methods _onResize and _refresh?

Thank you veru much.

**Comment by jmeinke** [comment] 2020-05-08 13:50
I can confirm this error.

**Closed** 2020-10-20 17:25 UTC
Labels: wontfix
